name       : xset
version    : 1.2.4
release    : 7
source     :
    - https://www.x.org/releases/individual/app/xset-1.2.4.tar.gz : 3a05e8626298c7a79002ec5fb4949dcba8abc7a2b95c03ed5e0f5698c3b4dea0
license    : GPL-3.0-or-later
component  : xorg.apps
summary    : X.Org Applications - xset
description: |
    X.Org Applications: xset
builddeps  :
    - pkgconfig(xproto)
    - pkgconfig(xmuu)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
