name       : xset
version    : 1.2.5
release    : 9
source     :
    - https://www.x.org/releases/individual/app/xset-1.2.5.tar.gz : 2068d1356d80c29ce283f0fff5895667b38f24ea95df363d3dde7b8c8a92fffe
license    : GPL-3.0-or-later
component  : xorg.apps
summary    : X.Org Applications - xset
description: |
    xset is used to set various user preference options of the X server
builddeps  :
    - pkgconfig(xproto)
    - pkgconfig(xmuu)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
