name        : xset
version     : 1.2.3
release     : 2
source     :
    - http://xorg.freedesktop.org/archive/individual/app/xset-1.2.3.tar.bz2 : 4382f4fb29b88647e13f3b4bc29263134270747fc159cfc5f7e3af23588c8063
license     : GPL-3.0+
summary     : X.Org Applications - xset
builddeps   :
    - pkgconfig(xproto)
    - pkgconfig(xmuu)
description : |
    X.Org Applications: xset
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
